### ISSUE TITLE
simply config

### ISSUE THREAD

**Issue by gr2m** [standard-release/app#3]
There is a built in method `context.config('your-config-file.yml', defaultOptions` which will load configuration from the context repository at the path `.github/your-config-file.yml`: https://probot.github.io/api/latest/Context.html#config

I think you can simplify your code here quite a bit with it

https://github.com/tunnckoCore/semantic-release-app/blob/5e2a40f6d232d6ff514a73ada957b6f15cf6366e/src/lib/config.js#L31-L46

**Comment by tunnckoCore** [comment]
Oh yea, i thought about it, but just forgot :D 
Thanks! Fresh view is always a good thing :)
